title: Knight Extension
description: Documentation for the Knight phishing protection Chrome extension
remote_theme: just-the-docs/just-the-docs

url: ""

nav_sort: case_insensitive

footer_content: "Knight Extension &copy; 2025"

search_enabled: true

color_scheme: dark

aux_links:
  "View on GitHub":
    - "https://github.com/5odead/KnightJS"

aux_links_new_tab: true
